language: android
jdk: oraclejdk7

android:
  components:
    - platform-tools
    - build-tools-20
    - build-tools-19.1.0
    - android-16
    - android-19
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.*

install: true # Override install task to prevent duplicate assembleDebug task invocation

script: ./gradlew testDebug --info
